language: node_js
node_js:
  - '8'
env:
  global:
    # kosssi GITHUB_TOKEN
    - secure: "pO6f6oUsLprIUDjPUHIdyuTbrITWcPvyFLT6rU7GkDcldtKBT2s2/vo7DBJlQWHAmzy4vqhRcBnESfVQtRXqE2O1G/7vhEb1cW2LNhFKZsbjks/niak5jJFdvkFH+Y5abu27Pg+mRaQ5q27BAt8MVYkJ4ndYX+0LBEv7jVn7GTuT8gNdDjOd7is4UUczccTHcn0sCuu9BAqkOTWjDxVI0q7njpapcnocA+cMTVvwUuS0TXRYz4q/xg/Vsb9MP3VrPO0ilK1L35JJBq6Vhdc7aYT703chRhk7GzPl5GEwOsD1NewmuQxzWpuKtobtLxYfVSq3+8P5PvsNyzzvFMcFBvjDMkwhPBDx0QvUwdd71KGZ3bV2l6YN+BdJjjsYC0rcOIU669+IMGwA+e1vw5giEr/npOeOTsLB5sBYH0q6BM915FCFAYOBFle36i5bsmJznsTzMHjioWyvsAhSzH1oaZ/swUcljrSnMG1MMumu5tVSQ4zEcea/4y/ZONvAwhp6uhQdyrGet7LyTs4rpTwsZQK1q1+V2BG0uQxOdtIPm/xSW4hkd4jGH2TPPWYwSvd+TWoRhTqkqkjFszCih+fdmASThXULzwJt3uZQfPhW5WHikUEktZKaP3PIfO5O6jwBwKGnhIQIdddZ+gPGGhLGOrNqRJwAKbgpwNcN5p1EviM="
    # REGISTRY_TOKEN
    - secure: DG/JzD0+x2NEzb9XL6VhvqGui1PumHbk4tX0eurIjSLmoLN41Gwsn1iuUqSUkV4DJJXjy12RtR6iz3GjhjcQGx1euPO+RKBpqn+DGyMdLqCTKkRe4gSocb6bQEewKXRYMaq79oOtlQxpES9vISKBUBF3JncumnZWfiwlo5A25QxhVZ+OUz4fAtjaZGeSA1Le/oWtUbpK4ODBStjhqXFDFkNparwF3MYtaptUf8XZJRCli+6fktt/yjGBG/WcRVhTrn+WZaBbHFU+uNflWeDO/xYEUVz5JvH0YXJwxW7ver2wfRRlHkJOAL+S2GVPikJFjiTtciCTVtJhZkywAConN2fbGqljTxDBGHr4gah87StzbjUH+0Szk4CVxHv2kfpmHHFuEgDzpAxyemfLk1Gj6Tx6VGKf9HS65sq7JKaIlABe+wNkSLXhucmZ/0qtMN0lNAPT1pTA6GXNtOu/ERoJ9v/iFmCK+TxTTLpA97BYq9pl6Wh82jdaROZTrywrCnYb2/sHb8Jzcqths9W+9BLfQFMWTrgYpmsWwkxyqJisz8mZzYubVO8l0kY1Meu5JNAcPpI+NicwTsMvsGy8Ux4Sv87Keo9acnxzpqs47HVNzPNUTJUFoyuASZCYXCfr2AI37kFon94dbAc4W+DgM1LLDIuwe/RcT3kDrkONMenzjEY=
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-malakoffmederic
    skip-cleanup: true
    script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-malakoffmederic
    skip-cleanup: true
    script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
    on:
      tags: true
